table 'grupitoo_kv fact_kv'
	lineageTag: 0790d168-e311-4134-bd9a-3ec607babc4b

	column fk_quarter_id
		dataType: dateTime
		formatString: Long Date
		lineageTag: a87df17a-29b9-4a04-a2e9-aeeb64c2dace
		summarizeBy: none
		sourceColumn: fk_quarter_id

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_count
		dataType: int64
		formatString: 0
		lineageTag: 8405eb27-3977-47c1-8527-1b3d2fe16062
		summarizeBy: sum
		sourceColumn: transaction_count

		annotation SummarizationSetBy = Automatic

	column fk_county_id
		dataType: int64
		formatString: 0
		lineageTag: 4911c464-990d-45c3-949f-b8c9d7a6f5ca
		summarizeBy: none
		sourceColumn: fk_county_id

		annotation SummarizationSetBy = Automatic

	column avg_price_m2
		dataType: double
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: f850ccfc-35ca-4ce3-9ed0-ac1e94980087
		summarizeBy: sum
		sourceColumn: avg_price_m2

		annotation SummarizationSetBy = Automatic

	partition 'grupitoo_kv fact_kv' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "postgres"),
				    grupitoo_kv_fact_kv = Source{[Schema="grupitoo_kv",Item="fact_kv"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(grupitoo_kv_fact_kv,{"grupitoo_kv.dim_county", "grupitoo_kv.dim_time"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

