/// Faktitabeli fact_palk grain on ühe maakonna keskmine brutopalk ühes kvartalis. 3 veergu, 1290 rida. Ajaperiood 2005-2026 (kaks esimest kvartalit), 15 maakonda.
table 'grupitoo_kv fact_palk'
	lineageTag: 1dadcdcc-fee7-4ecd-ba61-826922285f37

	/// Kvartali tunnus on kuupäeva formaadis, iga kvartali esimene kuupäev.
	column fk_quarter_id
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 63d00476-050a-408f-ae77-2df62fc60441
		summarizeBy: none
		sourceColumn: fk_quarter_id

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	/// Keskmine brutokuupalk kvartalite ja maakondade lõikes.
	column average_salary
		dataType: int64
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 4cca1c55-ff18-4129-b5c9-2d7f46e557f0
		summarizeBy: sum
		sourceColumn: average_salary

		annotation SummarizationSetBy = Automatic

	/// 1-Harju maakond, 2-Hiiu maakond, 3-Ida-Viru maakond, 4-Jõgeva maakond, 5-Järva maakond, 6-Lääne-Viru maakond, 7-Lääne maakond, 8-Põlva maakond, 9-Pärnu maakond, 10-Rapla maakond, 11-Saare maakond, 12-Tartu maakond, 13-Valga maakond, 14-Viljandi maakond, 15-Võru maakond
	column fk_county_id
		dataType: int64
		formatString: 0
		lineageTag: 550b62e8-603b-414a-954b-c15ae588e361
		summarizeBy: none
		sourceColumn: fk_county_id

		annotation SummarizationSetBy = Automatic

	partition 'grupitoo_kv fact_palk' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "postgres"),
				    grupitoo_kv_fact_palk = Source{[Schema="grupitoo_kv",Item="fact_palk"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(grupitoo_kv_fact_palk,{"grupitoo_kv.dim_county", "grupitoo_kv.dim_time"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

