[theme]
primaryColor = "#2b5c8f"            # Tumesinine aktsent
backgroundColor = "#faf9f6"         # Väga pehme ja stiilne valkjas-beež/kalgitaust
secondaryBackgroundColor = "#edf0f2" # Rahulik ja puhas hele-hall küljepaneel
textColor = "#2d3748"               # Pehme mustjashall tekst, mis loetav igal taustal
font = "sans serif"